server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: PRODUCT-SERVICE

eureka:
  instance:
    prefer-ip-address: true  # Sử dụng IP thay vì hostname khi đăng ký với Eureka
  client:
    fetch-registry: true      # Cho phép lấy danh sách service từ Eureka Server
    register-with-eureka: true # Cho phép đăng ký service vào Eureka Server
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

