server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/paymentdb
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  cloud:
    discovery:
      client:
        simple:
          instances:
            order-service:
              - uri: http://order-service:8082
management:
  endpoints:
    web:
      exposure:
        include: "*"  # B?t toàn b? actuator endpoints
  tracing:
    sampling:
      probability: 1.0  # Thu th?p 100% request
  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411/api/v2/spans

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full  # Log Feign request/response
  loadbalancer:
    enabled: true  # Quan tr?ng! B?t LoadBalancer ?? gi? traceId

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    io.micrometer.tracing: DEBUG
    reactor.netty.http.client: DEBUG
